### ISSUE TITLE
Build custom database

### ISSUE THREAD

**Issue by thbtmntgn** [prophyle/prophyle#298]
I'm trying to build a custom database.

Based on your documentation (https://prophyle.github.io/custom_db.html) I succeed to: 
1) Download and extract sequences
2) Index sequences with _samtools faidx_
3) Generate the _acc2taxid.tsv_ file

My problem is with the _prophyle_ncbi_tree.py_ script. Taxids are not found for every sequence (accession number). I got error message like this:

> [prophyle_ncbi_tree] ERROR: TaxID not found for sequence XXX_XXXXXXXX

Even if _XXX_XXXXXXXX.version_ is available in the _acc2taxid.tsv_ file

**First question**: is it possible that this problem is because the acc2taxid.tsv file contains _accession.version_ number instead of _accession_ number only?

**Second question**: Also, I'm not sure to understand the first 2 parameters needed by _prophyle_ncbi_tree.py_.
What's expected for <library_name> and _<library_main_dir>_ ? _<library_name>_ must be just a directory name and _<library_main_dir>_ must be the full path to this directory name?

**Last question**: is it possible to select an existing NCBI taxonomy instead of automatically download a new one in the current working directory?

**Comment by simonepignotti** [comment]
Hi Thibaut,

I am sorry to hear you had issues with that, we are about to release an update of that script to make the creation of custom databases much easier.
You actually identified the problem correctly, it is an inconsistence with the version of the accession numbers. Please try to use the following command to create the file `ftpselection.tsv`, then generate `acc2taxid.tsv` using the command in the docs:
```
awk -F "\t" -v OFS="\t" '$5=="reference genome" {split($1, a, "."); print a[1], $6, $20}' assembly_summary.txt >ftpselection.tsv
cut -f 1,2 ftpselection.tsv >acc2taxid.tsv
```
That will remove the version from the `acc2taxid.tsv` file. You don't need to recreate the fasta indexes nor to download the sequences again.
Also, since strain TaxIDs are deprecated since a while, my advice is to use `$7` instead of `$6` in the awk command, so that all the genomes will be linked to their species node (unless you are interested in strain-level classification, of course).

Concerning the parameters, `library_name` is the name of the subdirectory where the sequences are downloaded (e.g. bacteria, archaea, viral for the standard DBs, or any name of your choice), which will be prepended to the filenames in the tree. `library_main_dir` is the directory where all the sequences are downloaded, which usually is the parent of `library_name`. This should be used at indexing time (the `-g` parameter of `prophyle index`), unless the tree is placed in the very same directory.
Also these two parameters will be simplified, I understand they could be misleading.

The NCBI taxonomy is not downloaded automatically, unless the file `~/.etetoolkit/taxa.sqlite` does not exist. `ete3` is the library we rely upon to build the trees, and you can find some additional information here:
http://etetoolkit.org/docs/latest/tutorial/tutorial_ncbitaxonomy.html
In particular, to update the database using a specific version of the file `taxdump.tar.gz` distributed by NCBI, you can run the following commands in a python3 environment:
```
from ete3 import NCBITaxa
ncbi = NCBITaxa()
ncbi.update_taxonomy_database("path/to/taxdump.tar.gz")
```
This part is not well documented, but the code is here and the comments are quite clear:
https://github.com/etetoolkit/ete/blob/master/ete3/ncbi_taxonomy/ncbiquery.py

I hope that helps. Please tell me if you still have problems with it, and thanks for reporting this.
Simone

**Comment by thbtmntgn** [comment]
Awesome! Thank you for your answer I'm testing it right now!

Have you an estimated date for the next update?

**Comment by simonepignotti** [comment]
Great.
Not exactly, but hopefully sometime in May!
